### ISSUE TITLE
Segfault trying to open Output devices

### ISSUE THREAD

**Issue by C0rn3j** [saivert/pwvucontrol#45]
Flatpak pwvucontrol.  
Was clicking on the Output devices tabs to switch to it, instacrash.  
After switching from and between recording/input/output tab and config, turning my BT headset from LDAC to mSBC and back.

Can't reproduce.

```yaml
[340840.385750] pwvucontrol[2113252]: segfault at 7ffffeb2 ip 000072940aaba37f sp 00007ffecf70c3d0 error 4 in libgtk-4.so.1.1400.5[2ba37f,72940a8c7000+4c3000] likely on CPU 4 (core 4, socket 0)
[340840.385761] Code: 3a 48 89 df e8 72 fe ff ff 85 c0 74 23 48 63 15 37 82 8f 00 48 89 d8 eb 0e 66 90 48 8b 80 e0 00 00 00 48 85 c0 74 3c 48 01 d0 <f6> 40 02 40 75 eb 48 8b 5d f8 31 c0 c9 c3 0f 1f 00 48 8d 15 7d 8a
```

```yaml
# flatpak-coredumpctl -m 2113252 com.saivert.pwvucontrol
Core was generated by `pwvucontrol'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000072940aaba37f in gtk_widget_grab_focus () from /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
[Current thread is 1 (Thread 0x729408bb1f00 (LWP 2))]
(gdb) bt
#0  0x000072940aaba37f in gtk_widget_grab_focus () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#1  0x000072940b4902dc in set_visible_child.part () at /usr/lib/x86_64-linux-gnu/libadwaita-1.so.0
#2  0x000072940b4921e0 in adw_view_stack_pages_select_item () at /usr/lib/x86_64-linux-gnu/libadwaita-1.so.0
#3  0x000072940a3da6fa in g_closure_invoke () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#4  0x000072940a3f03bc in signal_emit_unlocked_R.isra.0 () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x000072940a3f1e41 in signal_emit_valist_unlocked () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#6  0x000072940a3f7e11 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#7  0x000072940a3f7ed3 in g_signal_emit () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#8  0x000072940a3ded54 in g_object_dispatch_properties_changed () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#9  0x000072940a3e31e3 in g_object_notify_by_pspec () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#13 0x000072940a3f7ed3 in <emit signal '???' on instance ???> () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #10 0x000072940a3da912 in _g_closure_invoke_va () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #11 0x000072940a3f1eff in signal_emit_valist_unlocked () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #12 0x000072940a3f7e11 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#18 0x000072940a3f7ed3 in <emit signal '???' on instance ???> () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #14 0x000072940a8d9523 in _gtk_marshal_VOID__INT_DOUBLE_DOUBLEv () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
    #15 0x000072940a3da912 in _g_closure_invoke_va () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #16 0x000072940a3f1eff in signal_emit_valist_unlocked () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #17 0x000072940a3f7e11 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#19 0x000072940a9925e3 in gtk_gesture_click_end () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#24 0x000072940a3f7ed3 in <emit signal '???' on instance ???> () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #20 0x000072940a3ddd5a in g_cclosure_marshal_VOID__BOXEDv () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #21 0x000072940a3da912 in _g_closure_invoke_va () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #22 0x000072940a3f1eff in signal_emit_valist_unlocked () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #23 0x000072940a3f7e11 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#25 0x000072940a98f2f8 in _gtk_gesture_check_recognized () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#26 0x000072940a990b4b in gtk_gesture_handle_event () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#27 0x000072940a993ded in gtk_gesture_single_handle_event () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#28 0x000072940a95d2af in gtk_event_controller_handle_event () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#29 0x000072940aab8cd8 in gtk_widget_run_controllers () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#30 0x000072940aac0dc2 in _gtk_widget_captured_event () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#31 0x000072940a9d54d2 in gtk_propagate_event_internal () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#32 0x000072940a9d5cfc in gtk_main_do_event () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#38 0x000072940a3f7ed3 in <emit signal '???' on instance ???> () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #33 0x000072940ac5bd2c in _gdk_marshal_BOOLEAN__POINTERv () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
    #34 0x000072940aced8a8 in gdk_surface_event_marshallerv () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
    #35 0x000072940a3da912 in _g_closure_invoke_va () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #36 0x000072940a3f1203 in signal_emit_valist_unlocked () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
    #37 0x000072940a3f7e11 in g_signal_emit_valist () at /usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0
#39 0x000072940acf13b7 in gdk_surface_handle_event () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#40 0x000072940ac72ae6 in gdk_event_source_dispatch () at /usr/lib/x86_64-linux-gnu/libgtk-4.so.1
#41 0x000072940a2d2697 in g_main_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#42 0x000072940a2d47b7 in g_main_context_iterate_unlocked.isra () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#43 0x000072940a2d4e73 in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#44 0x000072940a52014d in g_application_run () at /usr/lib/x86_64-linux-gnu/libgio-2.0.so.0
#45 0x00005c58ba52bbe7 in pwvucontrol::application::PwvucontrolApplication::run ()
#46 0x00005c58ba51de19 in pwvucontrol::main ()
#47 0x00005c58ba54b153 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#48 0x00005c58ba52e119 in std::rt::lang_start::{{closure}} ()
#49 0x00005c58ba586090 in std::rt::lang_start_internal ()
#50 0x00005c58ba51f375 in main ()
(gdb) 
```

```yaml
[0] % coredumpctl info 2113252 
           PID: 2113252 (pwvucontrol)
           UID: 1000 (c0rn3j)
           GID: 1000 (c0rn3j)
        Signal: 11 (SEGV)
     Timestamp: Mon 2024-10-07 18:05:48 CEST (1min 42s ago)
  Command Line: pwvucontrol
    Executable: /app/bin/pwvucontrol
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-flatpak-com.saivert.pwvucontrol-2113241.scope
          Unit: user@1000.service
     User Unit: app-flatpak-com.saivert.pwvucontrol-2113241.scope
         Slice: user-1000.slice
     Owner UID: 1000 (c0rn3j)
       Boot ID: a86dc5f168644dc4a5097555941181e6
    Machine ID: 80b78008ba8a4a6888c3be0a41f226e1
      Hostname: Luxuria
       Storage: /var/lib/systemd/coredump/core.pwvucontrol.1000.a86dc5f168644dc4a5097555941181e6.2113252.1728317148000000.zst (present)
  Size on Disk: 56.3M
       Message: Process 2113252 (pwvucontrol) of user 1000 dumped core.
                
                Module /app/bin/pwvucontrol without build-id.
                Module /app/bin/pwvucontrol
                Stack trace of thread 2:
                #0  0x000072940aaba37f n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x2ba37f)
                #1  0x000072940b4902dc n/a (/usr/lib/x86_64-linux-gnu/libadwaita-1.so.0 + 0xb52dc)
                #2  0x000072940b4921e0 n/a (/usr/lib/x86_64-linux-gnu/libadwaita-1.so.0 + 0xb71e0)
                #3  0x000072940a3da6fa n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x186fa)
                #4  0x000072940a3f03bc n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x2e3bc)
                #5  0x000072940a3f1e41 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x2fe41)
                #6  0x000072940a3f7e11 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x35e11)
                #7  0x000072940a3f7ed3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x35ed3)
                #8  0x000072940a3ded54 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x1cd54)
                #9  0x000072940a3e31e3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x211e3)
                #10 0x000072940a3da912 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x18912)
                #11 0x000072940a3f1eff n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x2feff)
                #12 0x000072940a3f7e11 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x35e11)
                #13 0x000072940a3f7ed3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x35ed3)
                #14 0x000072940a8d9523 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0xd9523)
                #15 0x000072940a3da912 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x18912)
                #16 0x000072940a3f1eff n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x2feff)
                #17 0x000072940a3f7e11 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x35e11)
                #18 0x000072940a3f7ed3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x35ed3)
                #19 0x000072940a9925e3 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x1925e3)
                #20 0x000072940a3ddd5a n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x1bd5a)
                #21 0x000072940a3da912 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x18912)
                #22 0x000072940a3f1eff n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x2feff)
                #23 0x000072940a3f7e11 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x35e11)
                #24 0x000072940a3f7ed3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x35ed3)
                #25 0x000072940a98f2f8 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x18f2f8)
                #26 0x000072940a990b4b n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x190b4b)
                #27 0x000072940a993ded n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x193ded)
                #28 0x000072940a95d2af n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x15d2af)
                #29 0x000072940aab8cd8 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x2b8cd8)
                #30 0x000072940aac0dc2 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x2c0dc2)
                #31 0x000072940a9d54d2 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x1d54d2)
                #32 0x000072940a9d5cfc n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x1d5cfc)
                #33 0x000072940ac5bd2c n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x45bd2c)
                #34 0x000072940aced8a8 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x4ed8a8)
                #35 0x000072940a3da912 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x18912)
                #36 0x000072940a3f1203 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x2f203)
                #37 0x000072940a3f7e11 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x35e11)
                #38 0x000072940a3f7ed3 n/a (/usr/lib/x86_64-linux-gnu/libgobject-2.0.so.0.8000.5 + 0x35ed3)
                #39 0x000072940acf13b7 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x4f13b7)
                #40 0x000072940ac72ae6 n/a (/usr/lib/x86_64-linux-gnu/libgtk-4.so.1.1400.5 + 0x472ae6)
                #41 0x000072940a2d2697 n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.5 + 0x60697)
                #42 0x000072940a2d47b7 n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.5 + 0x627b7)
                #43 0x000072940a2d4e73 n/a (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0.8000.5 + 0x62e73)
                #44 0x000072940a52014d n/a (/usr/lib/x86_64-linux-gnu/libgio-2.0.so.0.8000.5 + 0xf814d)
                #45 0x00005c58ba52bbe7 n/a (/app/bin/pwvucontrol + 0xe0be7)
                ELF object binary architecture: AMD x86-64
```

---

Side note, [Flatpak debug docs](https://docs.flatpak.org/en/latest/debugging.html) are bad as the recommended command will try to download 7GB+ for aarch64 SDK and also the x32 SDK...

I simply did it myself:
```bash
flatpak install org.gnome.Sdk
flatpak install com.saivert.pwvucontrol.Debug
```
